dist: xenial
language: node_js
node_js:
   - "8"
before_script:
  - npm install
  - npm run build
cache:
  directories:
    - ~/.npm
notifications:
  email: true
# Taken from:  https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/master/.travis.yml#L3

#trying test
